### ISSUE TITLE
"npm-dts generate" generates a reference to a non-existent module

### ISSUE THREAD

**Issue by chuacw** [vytenisu/npm-dts#32] opened 2022-04-24 04:03 UTC
npm-dts generates a reference to a non-existent module.

-- Files --
d----           20/4/2022  2:32 PM                node_modules
-a---           20/4/2022 10:11 AM             66 .gitattributes
-a---           20/4/2022 12:15 PM             50 .gitignore
-a---           24/4/2022 11:24 AM            201 logutils.ts
-a---           20/4/2022  2:32 PM            889 package-lock.json
-a---           24/4/2022 11:20 AM           1118 package.json
-a---           20/4/2022  5:20 PM            566 README.MD
-a---           20/4/2022 11:51 AM            515 rtl.ts
-a---           20/4/2022  2:24 PM            477 sysutils.ts
-a---           20/4/2022  5:47 PM           1416 tsconfig.json

-- package.json contents --
```

{
  "name": "delphirtl",
  "version": "1.0.33",
  "description": "RTL functions",
  "main": "",
  "types": "./index.d.ts",
  "exports": {
    "./logutils": {
      "import": "./lib/logutils.js",
      "require": "./lib/logutils.js"
    },
    "./rtl": {
      "import": "./lib/rtl.js",
      "require": "./lib/rtl.js"
    },
    "./sysutils": {
      "import": "./lib/sysutils.js",
      "require": "./lib/sysutils.js"
    }
  },
  "scripts": {
    "prepare": "del lib /s /q && tsc --build && npm-dts -o lib\\index.d.ts generate",
    "build": "tsc",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/chuacw/delphirtl.git"
  },
  "keywords": [
    "delphi",
    "rtl"
  ],
  "files": [
    "lib/**/*"
  ],
  "author": "chuacw",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/chuacw/delphirtl/issues"
  },
  "homepage": "https://github.com/chuacw/delphirtl#readme",
  "dependencies": {
    "@types/node": "^17.0.25"
  },
  "devDependencies": {
    "tsc": "^2.0.4",
    "typescript": "^4.6.3"
  },
  "type": "module"
}

```

Running npm-dts generates creates...  index.d.ts which has the following content:
```
declare module 'delphirtl/logutils' {
  function log(arg: any): void;
  function info(arg: any): void;
  function error(arg: any): void;
  export { info, error, log };

}
declare module 'delphirtl/rtl' {
  function ParamCount(): number;
  function ParamStr(index: number): string;
  export { ParamCount, ParamStr, ParamCount as getParamCount, ParamStr as getParamStr };

}
declare module 'delphirtl/sysutils' {
  function extractFileDir(AFilename: string): string;
  function extractFileName(AFileName: string): string;
  export { extractFileDir, extractFileName, extractFileDir as ExtractFileDir, extractFileName as ExtractFileName };

}
declare module 'delphirtl' {
  import main = require('delphirtl/index');
  export = main;
}
```
But "delphirtl/index" doesn't exist, as this is the contents of the directory after running "npm-dts generate":

d----           20/4/2022  2:32 PM                node_modules
-a---           20/4/2022 10:11 AM             66 .gitattributes
-a---           20/4/2022 12:15 PM             50 .gitignore
-a---           24/4/2022 12:00 PM            730 index.d.ts
-a---           24/4/2022 11:24 AM            201 logutils.ts
-a---           20/4/2022  2:32 PM            889 package-lock.json
-a---           24/4/2022 11:20 AM           1118 package.json
-a---           20/4/2022  5:20 PM            566 README.MD
-a---           20/4/2022 11:51 AM            515 rtl.ts
-a---           20/4/2022  2:24 PM            477 sysutils.ts
-a---           20/4/2022  5:47 PM           1416 tsconfig.json

**Comment by vytenisu** [comment] 2022-05-02 11:02
Hello, thank you for your report. Issue seems duplicate of https://github.com/vytenisu/npm-dts/issues/29. I am planning to check it out sometime very soon. Had a bit hectic time schedule recently - sry for delay.

Closing because it is a duplicate of: https://github.com/vytenisu/npm-dts/issues/29. Will add a back-link to this task as well.

**Closed by vytenisu** 2022-05-02 11:02 UTC

**Comment by vytenisu** [comment] 2022-05-02 15:33
**npm-dts** is designed for single-entry point libraries. Therefor you need one of your files to be the entry/main file which (re)exports everything that is needed. By default **npm-dts** assumes that your entry file is _index.ts_ but since you do not have one - it is causing you trouble.

Try creating index.ts like this:

```
export * from './logutils'
export * from './sysutils'
export * from './rtl'
```

**Comment by vytenisu** [comment] 2022-05-02 15:35
Please feel free to re-open should this not solve your problem.
