### ISSUE TITLE
Correct main declaration

### ISSUE THREAD

**Issue by JakeAdler** [vytenisu/npm-dts#14] opened 2021-02-10 01:09 UTC
https://github.com/vytenisu/npm-dts/blob/f2144302c4edb1d017dd2ba58f518a8c6d0f137d/lib/generator.ts#L590-L592

This produces output which  throws a ts-error
```
[tsserver 2691] An import path cannot end with a '.ts' extension. Consider importing '@package/` instead.    
```
Can be fixed with something like this 
```ts
declare module '${packageDetails.name}' { 
    export * from '${mainFileWithoutExtension}')
}
```

**Comment by vytenisu** [comment] 2021-02-10 07:56
I have checked a few modules where npm-dts is used - extension was not added in them. I have a suspicion that full path of entry file might not be resolved correctly. If npm-dts does not find the file specified - it might leave the extension present. I will need additional information in order to advice and/or reproduce the issue:

1. What is your entry file name and ideally - full path?
2. What is the root of your project (where package.json is)?
3. How are you launching npm-dts - what is the current working directory?
4. Have you manually changed root path of your project by passing -root?

**Comment by vytenisu** [comment] 2021-02-10 09:04
@JakeAdler , please try **version 1.3.9** and let me know if it works.

I spotted that entry file was resolved relative to CWD while it should have been resolved relative to root path (which can be changed via CLI parameters).

I will close this ticket since issue seems identified. Please feel free to re-open in case issue persists.

**Closed by vytenisu** 2021-02-10 09:04 UTC
